# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a98e66df6a09a2341e86d7ac39fcf345c4065f324b28a3445f246f634a2a4c337de60be1eb1d27aff7de322fe6791a4391ed9e829c090c705b25f769953587c6

test:
  secret_key_base: db5b241f31addd433a06a332ab312dcfcfd40c5ffe20b91c92085f1c60b2912731f0847d991ec43ff85590b9bcafd9c74a488bc0ece8bb8c1ce42fdb426aa103

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
